"use client";

import { useState, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { Printer, Calendar } from "lucide-react";
import { fetchForecast } from "@/lib/api";
import { formatDate } from "@/lib/format-date";
import { getVariationSortIndex } from "@/lib/variation-order";

const PRODUCT_FILTERS = [
  { label: "All Products", value: "all" },
  { label: "Ube Halaya", value: "Ube Halaya" },
  { label: "Ube Jam", value: "Ube Jam" },
];

export default function QuotaPage() {
  const [selectedDate, setSelectedDate] = useState(() => {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    return tomorrow.toISOString().split("T")[0];
  });
  const [productFilter, setProductFilter] = useState("all");

  const { data, isLoading } = useQuery({
    queryKey: ["forecast", "quota", 30],
    queryFn: () => fetchForecast(30),
  });

  // Filter data for the selected date and product
  const quotaData = useMemo(() => {
    if (!data) return [];
    return data
      .filter((item) => item.date === selectedDate)
      .filter((item) => productFilter === "all" || item.product_name === productFilter)
      .map((item) => ({
        ...item,
        recommended_production: Math.ceil(item.upper_bound),
      }))
      .sort((a, b) => getVariationSortIndex(undefined, a.variation_id) - getVariationSortIndex(undefined, b.variation_id));
  }, [data, selectedDate, productFilter]);

  // Totals per product
  const productTotals = useMemo(() => {
    if (!data) return { halaya: 0, jam: 0, all: 0 };
    const dayData = data.filter((item) => item.date === selectedDate);
    const halaya = dayData.filter((d) => d.product_name === "Ube Halaya").reduce((sum, d) => sum + Math.ceil(d.upper_bound), 0);
    const jam = dayData.filter((d) => d.product_name === "Ube Jam").reduce((sum, d) => sum + Math.ceil(d.upper_bound), 0);
    return { halaya, jam, all: halaya + jam };
  }, [data, selectedDate]);

  const handlePrint = () => window.print();

  return (
    <div className="space-y-6 page-enter">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 animate-fade-in print:hidden">
        <div>
          <h1 className="text-xl font-semibold text-gray-900 dark:text-gray-50">Manufacturing Quota</h1>
          <p className="text-[13px] text-gray-500 mt-1">AI-recommended daily production quantities</p>
        </div>
        <div className="flex items-center gap-3">
          {/* Product filter */}
          <div className="flex gap-1 bg-gray-100 dark:bg-gray-800 rounded-xl p-1">
            {PRODUCT_FILTERS.map((f) => (
              <button
                key={f.value}
                onClick={() => setProductFilter(f.value)}
                className={`px-3 py-2 rounded-lg text-[11px] font-medium transition-all btn-press ${
                  productFilter === f.value
                    ? "bg-brand-500 text-white shadow-md"
                    : "text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white"
                }`}
              >
                {f.label}
              </button>
            ))}
          </div>

          {/* Date picker */}
          <div className="flex items-center gap-2 px-3 py-2 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800">
            <Calendar size={14} className="text-gray-400" />
            <input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="text-[12px] bg-transparent text-gray-900 dark:text-gray-100 outline-none"
            />
          </div>

          <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-brand-500 text-white text-[12px] font-semibold btn-press shadow-[0_2px_8px_rgba(70,95,255,0.25)]"
          >
            <Printer size={14} />
            Print
          </button>
        </div>
      </div>

      {/* Print header */}
      <div className="hidden print:block print:mb-8">
        <h1 className="text-2xl font-bold text-center">Bren Raphael&apos;s Ube Halaya &amp; Jam Company</h1>
        <h2 className="text-lg text-center text-gray-600 mt-1">Daily Manufacturing Quota — {formatDate(selectedDate)}</h2>
        <p className="text-sm text-center text-gray-400 mt-1">Generated by POS-PROBE AI System</p>
      </div>

      {/* Product summary cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 animate-slide-up stagger-1 print:hidden">
        <div className="bg-white dark:bg-[#1a2231] border border-gray-200 dark:border-[#2d3748] rounded-2xl p-4 card-hover">
          <p className="text-[11px] text-gray-500 uppercase font-medium">Ube Halaya Total</p>
          <p className="text-xl font-bold text-gray-900 dark:text-gray-50 mt-1">{productTotals.halaya} units</p>
        </div>
        <div className="bg-white dark:bg-[#1a2231] border border-gray-200 dark:border-[#2d3748] rounded-2xl p-4 card-hover">
          <p className="text-[11px] text-gray-500 uppercase font-medium">Ube Jam Total</p>
          <p className="text-xl font-bold text-gray-900 dark:text-gray-50 mt-1">{productTotals.jam} units</p>
        </div>
        <div className="bg-white dark:bg-[#1a2231] border border-brand-200 dark:border-brand-500/30 rounded-2xl p-4 card-hover">
          <p className="text-[11px] text-brand-500 uppercase font-medium">Combined Total</p>
          <p className="text-xl font-bold text-brand-500 mt-1">{productTotals.all} units</p>
        </div>
      </div>

      {/* Quota Table */}
      <div className="bg-white dark:bg-[#1a2231] border border-gray-200 dark:border-[#2d3748] rounded-2xl p-6 card-hover animate-bounce-in stagger-2 print:border-none print:shadow-none print:p-0">
        {isLoading ? (
          <div className="h-[200px] shimmer rounded-xl flex items-center justify-center">
            <p className="text-[12px] text-gray-500">Loading quota data...</p>
          </div>
        ) : quotaData.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full text-[13px] print:text-[11px]">
              <thead>
                <tr className="border-b-2 border-gray-200 dark:border-gray-700">
                  <th className="text-left py-3 px-3 text-gray-600 dark:text-gray-400 font-semibold">Product Name</th>
                  <th className="text-left py-3 px-3 text-gray-600 dark:text-gray-400 font-semibold">Variation</th>
                  <th className="text-right py-3 px-3 text-gray-600 dark:text-gray-400 font-semibold">Predicted Demand</th>
                  <th className="text-right py-3 px-3 text-gray-600 dark:text-gray-400 font-semibold">Lower Estimate</th>
                  <th className="text-right py-3 px-3 text-gray-600 dark:text-gray-400 font-semibold">Upper Estimate</th>
                  <th className="text-right py-3 px-3 text-brand-600 dark:text-brand-400 font-bold">Recommended Production</th>
                </tr>
              </thead>
              <tbody>
                {quotaData.map((row) => (
                  <tr key={row.variation_id} className="border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors print:hover:bg-transparent">
                    <td className="py-3 px-3 text-gray-900 dark:text-gray-100 font-medium">{row.product_name}</td>
                    <td className="py-3 px-3 text-gray-700 dark:text-gray-300">{row.variation_name}</td>
                    <td className="py-3 px-3 text-right text-gray-900 dark:text-gray-100">{row.predicted_quantity} units</td>
                    <td className="py-3 px-3 text-right text-gray-500">{row.lower_bound} units</td>
                    <td className="py-3 px-3 text-right text-gray-500">{row.upper_bound} units</td>
                    <td className="py-3 px-3 text-right font-bold text-brand-600 dark:text-brand-400 text-[14px]">{row.recommended_production} units</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t-2 border-gray-300 dark:border-gray-600">
                  <td colSpan={5} className="py-3 px-3 font-semibold text-gray-900 dark:text-gray-100">Total Production</td>
                  <td className="py-3 px-3 text-right font-bold text-brand-600 dark:text-brand-400 text-[15px]">
                    {quotaData.reduce((sum, r) => sum + r.recommended_production, 0)} units
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        ) : (
          <div className="text-center py-12">
            <p className="text-[13px] text-gray-500">No quota data available for {formatDate(selectedDate)}.</p>
            <p className="text-[11px] text-gray-400 mt-1">Select a date within the next 30 days.</p>
          </div>
        )}
      </div>

      <p className="text-[11px] text-gray-400 print:hidden">
        💡 The &quot;Recommended Production&quot; uses the upper bound estimate, rounded up — producing slightly more than predicted is safer than stockouts.
      </p>
    </div>
  );
}
